Epoch 1/10:   0%|                                                                                                     | 0/1104 [00:30<?, ?it/s]
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/ileri_sayisal/train_hf.py", line 178, in <module>
    finetuner.train(train_loader, val_loader)
  File "/teamspace/studios/this_studio/ileri_sayisal/train_hf.py", line 70, in train
    for batch in pbar:
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1329, in _next_data
    idx, data = self._get_data()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1295, in _get_data
    success, data = self._try_get_data()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/queues.py", line 113, in get
    if not self._poll(timeout):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/wandb/sdk/lib/exit_hooks.py", line 52, in exc_handler
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/traceback.py", line 120, in print_exception
    for line in te.format(chain=chain):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/exceptiongroup/_formatting.py", line 248, in format
    yield from _ctx.emit(exc.format_exception_only())
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/exceptiongroup/_formatting.py", line 64, in emit
    for text in text_gen:
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/exceptiongroup/_formatting.py", line 335, in format_exception_only
    if isinstance(self.__notes__, collections.abc.Sequence):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/abc.py", line 119, in __instancecheck__
    return _abc_instancecheck(cls, instance)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/abc.py", line 121, in __subclasscheck__
    def __subclasscheck__(cls, subclass):
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/ileri_sayisal/train_hf.py", line 178, in <module>
    finetuner.train(train_loader, val_loader)
  File "/teamspace/studios/this_studio/ileri_sayisal/train_hf.py", line 70, in train
    for batch in pbar:
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1329, in _next_data
    idx, data = self._get_data()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1295, in _get_data
    success, data = self._try_get_data()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/queues.py", line 113, in get
    if not self._poll(timeout):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
